on:
  push:
    branches: [main]

name: Upload Release Asset

jobs:
  build_windows:
    name: Build .exe file
    runs-on: windows-latest
    steps:
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pyinstaller main.py --onefile
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows
          path: ./dist/main.exe